import { Inter } from "next/font/google"; // Google font import
import localFont from "next/font/local"; // SN Pro aksar local use hota hai ya specific handle hota hai
import "./globals.css";


// Font configuration
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
